class Card(object):
    def __init__(self, id: str, misc: int = 0, upgrades: int = 1) -> None:
        super().__init__()
        self.id = id
        self.misc = misc
        self.upgrades = upgrades

    def to_json(self):
        return {
            "id": self.id,
            "misc": self.misc,
            "upgrades": self.upgrades
        }

    class Ironclad:
        # Starter Cards
        BASH = "Bash"
        DEFEND_R = "Defend"
        STRIKE_R = "Strike"

        # Common Cards
        ANGER = "Anger"
        ARMAMENTS = "Armaments"
        BODY_SLAM = "Body Slam"
        CLASH = "Clash"
        CLEAVE = "Cleave"
        CLOTHESLINE = "Clothesline"
        FLEX = "Flex"
        HAVOC = "Havoc"
        HEADBUTT = "Headbutt"
        HEAVY_BLADE = "Heavy Blade"
        IRON_WAVE = "Iron Wave"
        PERFECTED_STRIKE = "Perfected Strike"
        POMMEL_STRIKE = "Pommel Strike"
        SHRUG_IT_OFF = "Shrug it Off"
        SWORD_BOOMERANG = "Sword Boomerang"
        THUNDERCLAP = "Thunderclap"
        TRUE_GRIT = "True Grit"
        TWIN_STRIKE = "Twin Strike"
        WARCRY = "Warcry"
        WILD_STRIKE = "Wild Strike"

        # Uncommon Cards
        BATTLE_TRANCE = "Battle Trance"
        BLOOD_FOR_BLOOD = "Blood for Blood"
        BLOODLETTING = "Bloodletting"
        BURNING_PACT = "Burning Pact"
        CARNAGE = "Carnage"
        COMBUST = "Combust"
        DARK_EMBRACE = "Dark Embrace"
        DISARM = "Disarm"
        DROPKICK = "Dropkick"
        DUAL_WIELD = "Dual Wield"
        ENTRENCH = "Entrench"
        EVOLVE = "Evolve"
        FEEL_NO_PAIN = "Feel No Pain"
        FIRE_BREATHING = "Fire Breathing"
        FLAME_BARRIER = "Flame Barrier"
        GHOSTLY_ARMOR = "Ghostly Armor"
        HEMOKINESIS = "Hemokinesis"
        INFERNAL_BLADE = "Infernal Blade"
        INFLAME = "Inflame"
        INTIMIDATE = "Intimidate"
        METALLICIZE = "Metallicize"
        POWER_THROUGH = "Power Through"
        PUMMEL = "Pummel"
        RAGE = "Rage"
        RAMPAGE = "Rampage"
        RECKLESS_CHARGE = "Reckless Charge"
        RUPTURE = "Rupture"
        SEARING_BLOW = "Searing Blow"
        SECOND_WIND = "Second Wind"
        SEEING_RED = "Seeing Red"
        SENTINEL = "Sentinel"
        SEVER_SOUL = "Sever Soul"
        SHOCKWAVE = "Shockwave"
        SPOT_WEAKNESS = "Spot Weakness"
        UPPERCUT = "Uppercut"
        WHIRLWIND = "Whirlwind"

        # Rare Cards
        BARRICADE = "Barricade"
        BERSERK = "Berserk"
        BLUDGEON = "Bludgeon"
        BRUTALITY = "Brutality"
        CORRUPTION = "Corruption"
        DEMON_FORM = "Demon Form"
        DOUBLE_TAP = "Double Tap"
        EXHUME = "Exhume"
        FEED = "Feed"
        FIEND_FIRE = "Fiend Fire"
        IMMOLATE = "Immolate"
        IMPERVIOUS = "Impervious"
        JUGGERNAUT = "Juggernaut"
        LIMIT_BREAK = "Limit Break"
        OFFERING = "Offering"
        REAPER = "Reaper"

    class Silent:
        # Starter Cards
        DEFEND_G = "Defend"
        NEUTRALIZE = "Neutralize"
        STRIKE_G = "Strike"
        SURVIVOR = "Survivor"

        # Common Cards
        ACROBATICS = "Acrobatics"
        BACKFLIP = "Backflip"
        BANE = "Bane"
        BLADE_DANCE = "Blade Dance"
        CLOAK_AND_DAGGER = "Cloak and Dagger"
        DAGGER_SPRAY = "Dagger Spray"
        DAGGER_THROW = "Dagger Throw"
        DEADLY_POISON = "Deadly Poison"
        DEFLECT = "Deflect"
        DODGE_AND_ROLL = "Dodge and Roll"
        FLYING_KNEE = "Flying Knee"
        OUTMANEUVER = "Outmaneuver"
        PIERCING_WAIL = "Piercing Wail"
        POISONED_STAB = "Poisoned Stab"
        PREPARED = "Prepared"
        QUICK_SLASH = "Quick Slash"
        SLICE = "Slice"
        SNEAKY_STRIKE = "Sneaky Strike"
        SUCKER_PUNCH = "Sucker Punch"

        # Uncommon Cards
        ACCURACY = "Accuracy"
        ALL_OUT_ATTACK = "All-Out Attack"
        BACKSTAB = "Backstab"
        BLUR = "Blur"
        BOUNCING_FLASK = "Bouncing Flask"
        CALCULATED_GAMBLE = "Calculated Gamble"
        CALTROPS = "Caltrops"
        CATALYST = "Catalyst"
        CHOKE = "Choke"
        CONCENTRATE = "Concentrate"
        CRIPPLING_CLOUD = "Crippling Cloud"
        DASH = "Dash"
        DISTRACTION = "Distraction"
        ENDLESS_AGONY = "Endless Agony"
        ESCAPE_PLAN = "Escape Plan"
        EVISCERATE = "Eviscerate"
        EXPERTISE = "Expertise"
        FINISHER = "Finisher"
        FLECHETTES = "Flechettes"
        FOOTWORK = "Footwork"
        HEEL_HOOK = "Heel Hook"
        INFINITE_BLADES = "Infinite Blades"
        LEG_SWEEP = "Leg Sweep"
        MASTERFUL_STAB = "Masterful Stab"
        NOXIOUS_FUMES = "Noxious Fumes"
        PREDATOR = "Predator"
        REFLEX = "Reflex"
        RIDDLE_WITH_HOLES = "Riddle With Holes"
        SETUP = "Setup"
        SKEWER = "Skewer"
        TACTICIAN = "Tactician"
        TERROR = "Terror"
        WELL_LAID_PLANS = "Well-Laid Plans"

        # Rare Cards
        A_THOUSAND_CUTS = "A Thousand Cuts"
        ADRENALINE = "Adrenaline"
        AFTER_IMAGE = "After Image"
        ALCHEMIZE = "Alchemize"
        BULLET_TIME = "Bullet Time"
        BURST = "Burst"
        CORPSE_EXPLOSION = "Corpse Explosion"
        DIE_DIE_DIE = "Die Die Die"
        DOPPELGANGER = "Doppelganger"
        ENVENOM = "Envenom"
        GLASS_KNIFE = "Glass Knife"
        GRAND_FINALE = "Grand Finale"
        MALAISE = "Malaise"
        NIGHTMARE = "Nightmare"
        PHANTASMAL_KILLER = "Phantasmal Killer"
        STORM_OF_STEEL = "Storm of Steel"
        TOOLS_OF_THE_TRADE = "Tools of the Trade"
        UNLOAD = "Unload"
        WRAITH_FORM = "Wraith Form"

    class Colorless:
        # Uncommon Cards
        BANDAGE_UP = "Bandage Up"
        BLIND = "Blind"
        DARK_SHACKLES = "Dark Shackles"
        DEEP_BREATH = "Deep Breath"
        DISCOVERY = "Discovery"
        DRAMATIC_ENTRANCE = "Dramatic Entrance"
        ENLIGHTENMENT = "Enlightenment"
        FINESSE = "Finesse"
        FLASH_OF_STEEL = "Flash of Steel"
        FORETHOUGHT = "Forethought"
        GOOD_INSTINCTS = "Good Instincts"
        IMPATIENCE = "Impatience"
        JACK_OF_ALL_TRADES = "Jack Of All Trades"
        MADNESS = "Madness"
        MIND_BLAST = "Mind Blast"
        PANACEA = "Panacea"
        PANIC_BUTTON = "Panic Button"
        PURITY = "Purity"
        SWIFT_STRIKE = "Swift Strike"
        TRIP = "Trip"

        # Rare Cards
        APOTHEOSIS = "Apotheosis"
        CHRYSALIS = "Chrysalis"
        HAND_OF_GREED = "Hand of Greed"
        MAGNETISM = "Magnetism"
        MASTER_OF_STRATEGY = "Master Of Strategy"
        MAYHEM = "Mayhem"
        METAMORPHOSIS = "Metamorphosis"
        PANACHE = "Panache"
        SADISTIC_NATURE = "Sadistic Nature"
        SECRET_TECHNIQUE = "Secret Technique"
        SECRET_WEAPON = "Secret Weapon"
        THE_BOMB = "The Bomb"
        THINKING_AHEAD = "Thinking Ahead"
        TRANSMUTATION = "Transmutation"
        VIOLENCE = "Violence"

        # Special Cards
        APPARITION = "Apparition"
        BETA = "Beta"
        BITE = "Bite"
        EXPUNGER = "Expunger"
        INSIGHT = "Insight"
        JAX = "J.A.X."
        MIRACLE = "Miracle"
        OMEGA = "Omega"
        RITUAL_DAGGER = "Ritual Dagger"
        SAFETY = "Safety"
        SHIV = "Shiv"
        SMITE = "Smite"
        THROUGH_VIOLENCE = "Through Violence"
